[WIP] Update TextModels to work with Flux @0.12 and Zygote
JuliaText/TextModels.jl pull request #20
Opened 2021-04-29 05:35 UTC by AdarshKumar712

This PR updates the current version of the models available with TextModels.jl to work with Flux@0.12 and Zygote. Will fix #1 and #19  

Models updated so far:
- [x] CRF
- [x] NER
- [x] POS
- [x] Sentiment.jl (no changes)
- [x] averagePerceptronTagger.jl (no changes)

Also updated Project.toml

Work to be done:
- [ ] Update ULMFit model
- [ ] Update Tests
- [ ] Update Docs

PS. Currently I have commented out the section of code belonging to ULMFit Model. Will uncomment it once its updated.

Please let me know if there are some mistakes. 
cc @aviks

2021-05-01 11:49 UTC, sambitdash commented
In #21, I have made some changes to ULMFit, CRF, NER and POS. Some test cases in NER, POS are broken and have been marked as well. I feel there may be a retraining needed for NER and POS as the model is changed in Flux for the LSTM. The precomputed weights are not good enough. The retrainable parameter logic is ULMFit is probably broken. That may not be needed as well. One can provide the `@functor` macro the relevant params to set the right retrainable parameters.

2021-05-01 13:58 UTC, AdarshKumar712 commented
I will surely look into the changes you made in your PR. Thanks a lot @sambitdash!

2021-05-18 14:44 UTC, AdarshKumar712 commented
Currently, CI build is giving a dependency error while precompiling because of `CorpusLoaders.jl` (used for ULMFit module). I have created an issue https://github.com/JuliaText/CorpusLoaders.jl/issues/43 regarding the same. Once the issue resolves, hopefully CI build will work properly. And accordingly, I will also update this PR.

2021-05-22 06:47 UTC, AdarshKumar712 commented
I am thinking to do the documentation update separately. Other than that, the rest is updated. @aviks can you once have a look?

2021-06-25 14:33 UTC, aviks commented
So @AdarshKumar712 is this ready to merge? There is a test failure in nightly, but I think that is an upstream issue.

2021-06-25 16:30 UTC, AdarshKumar712 commented
Yes, this is ready for now. If there will be any issues, that can be accommodated in future. On a side note, the ULMFiT model is a bit way too slow. So wasn't able to completely check for the Pretraining and fine-tuning. But rest works fine.

2021-06-30 13:11 UTC, tejasvaidhyadev requested changes

2021-06-30 13:11 UTC, tejasvaidhyadev commented on src/ULMFiT/custom_layers.jl
> +        reshape(zeros(Float32, out),out, 1),
reshape(zeros(Float32, out), out, 1),

2021-06-30 13:11 UTC, tejasvaidhyadev commented on src/ULMFiT/custom_layers.jl
> +# over definition for reset! to work with pretrained model
try using DocString

2021-06-30 13:11 UTC, tejasvaidhyadev commented on src/ULMFiT/fine_tune_lm.jl
>  To use this funciton, an instance of LanguageModel and a data loader is needed.
function* typo

2021-06-30 13:12 UTC, tejasvaidhyadev commented
looks good to me

2021-07-01 08:12 UTC, AdarshKumar712 commented
Updated as per the suggestions. Hopefully, now it's ready to merge.
cc @aviks @tejasvaidhyadev

2021-07-04 06:50 UTC, tejasvaidhyadev approved these changes
Looks good to me

2021-07-11 11:13 UTC, tejasvaidhyadev commented
@aviks 
should we merge it?

2021-07-11 14:53 UTC, aviks commented
Ok, here goes...

2021-07-11 14:53 UTC, merged